apiVersion: v1
kind: Service
metadata:
  name: image-scanner-service
  namespace: default
spec:
  selector:
    app: image-scanner
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
